### ISSUE TITLE
[Question] Pokecord -> Poketwo

### ISSUE THREAD

**Issue by kobe-hcjordao** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#187]
I have already got the bot for the Pokecord, I am wondering if it will work on the new Poketwo "mimic" of Pokecord?

**Comment by IceCruelStuff** [comment]
I thought Pokecord was shut down

**Comment by hcjordao** [comment]
New bot, pretty much copy of pokecord came out recently.

**Comment by Hyperclaw79** [comment]
Since the message content, embed styles, etc. might vary for every clone, it's not possible to create a universally working Selfbot. However, it should work for anything identical to the old pokecord, once you replace the hardcoded ID of pokecord. I'll consider adding this ID as a config parameter to make things more flexible. However, you'll most probably have to rehash all the Pokemons.

**Comment by Hyperclaw79** [comment]
Added the said feature in v6.1.4 - #190

**Comment by Hyperclaw79** [comment]
@kobe-hcjordao The Premium Version now supports autocatching for PokeTwo
